$(document).ready(function(){
    $('.forgot').click(function(){
        $('.step11').hide()
        $('.step12').show()
    })
    $(".cancelbtn-h").click(function(){
        $('.step11').show()
        $('.step12').hide()
    })
})